---
#
# This docker-compose.yml is for running the latest development version
# of An Otter Wiki.
#
# Please read the Installation guide <https://otterwiki.com/Installation>
# to get started.
#

services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./app-data:/app-data
      - ./custom-files:/app/otterwiki/static/custom
    
  # mount the local directory ./app-data into the container
      # (so settings, database and repository are accessible)
      


  #selenium-hub:
    #image: selenium/hub:latest
    #container_name: selenium-hub
    #ports:
     # - "4444:4444"
     # - "4442:4442"
     # - "4443:4443"

  chrome-browser:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  traffic-script:
    build: .
    volumes:
      - .:/app
    depends_on:
      - umami
      - chrome-browser


  umami:
      image: elestio/umami:latest
      ports:
        - "3000:3000"
      environment:
        DATABASE_URL: postgresql://umami:trust@db:5432/umami
        DATABASE_TYPE: postgresql
        DISABLE_BOT_CHECK: 1
        APP_SECRET: base
      depends_on:
        - db
      restart: always


  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: trust
    volumes:
    - ./umami-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  umami_db_data:
