#swap over to bind mounts instead of persistent volumes
#move it over to a completely unrelated directory and docker up to make sure it comes up with no issues
services:
  migrate:
    image: ghcr.io/plausible/community-edition:v3.2.0
    depends_on:
      - postgres
      - clickhouse
    restart: "no"
    command: >
      sh -c "sleep 10 &&
             /entrypoint.sh db createdb &&
             /entrypoint.sh db migrate"
    environment:
      BASE_URL: "http://localhost:8000"
      SECRET_KEY_BASE: "9f6a7c1e4d3b2a8f5e6d7c9b0a1f2e3d4c5b6a7988d7e6f5c4b3a2910e1d2c3f7a8b9c0d1e2f3a4b5c6d7e8f90123456"
      TOTP_VAULT_KEY: "LwqQb8n8zv8W2rWjYw0m2A6M0Gq1JvQ0Qj4x7LwqH7A="
      DATABASE_URL: "ecto://postgres:postgres@postgres:5432/plausible_db"
      CLICKHOUSE_DATABASE_URL: "http://plausible:plausiblepass@clickhouse:8123/plausible_events_db"
      DISABLE_REGISTRATION: "false"

  analytics:
    image: ghcr.io/plausible/community-edition:v3.2.0
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      BASE_URL: "http://localhost:8000"
      SECRET_KEY_BASE: "9f6a7c1e4d3b2a8f5e6d7c9b0a1f2e3d4c5b6a7988d7e6f5c4b3a2910e1d2c3f7a8b9c0d1e2f3a4b5c6d7e8f90123456"
      TOTP_VAULT_KEY: "LwqQb8n8zv8W2rWjYw0m2A6M0Gq1JvQ0Qj4x7LwqH7A="
      DATABASE_URL: "ecto://postgres:postgres@postgres:5432/plausible_db"
      CLICKHOUSE_DATABASE_URL: "http://plausible:plausiblepass@clickhouse:8123/plausible_events_db"
      DISABLE_REGISTRATION: "false"

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: plausible_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./plausible_postgres:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: plausible_events_db
      CLICKHOUSE_USER: plausible
      CLICKHOUSE_PASSWORD: plausiblepass
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - plausible_clickhouse:/var/lib/clickhouse

  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app-data:/app-data
      - ./custom:/app/otterwiki/static/custom

volumes:
  plausible_clickhouse: